apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: test-cronjob
  namespace: test
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          restartPolicy: OnFailure
          containers:
          - name: test-cronjob
            command: ["/bin/sh", "-c", "sleep 10; echo hello world"]
            image: alpine:latest
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 3
  suspend: false
