apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {cronjob_name}
  namespace: {ns}
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: {cronjob_name}
            # command: {cronjob_cmd}
            image: {docker_image}
  schedule: {schedule_expression}
  successfulJobsHistoryLimit: 3
  suspend: {suspend}
