apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: server
  name: server
spec:
  selector:
    matchLabels:
      k8s-app: server
  template:
    metadata:
      labels:
        k8s-app: server
    spec:
      containers:
      - image: ghcr.io/xuyang1996/server:67028d43c1f7d83c4c0f8b9fee7a89bf9ac767e3
        imagePullPolicy: IfNotPresent
        name: server
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    k8s-app: server
  ports:
  - name: default
    port: 9000
    targetPort: 9000