apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: server
  namespace: test
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: server
            image: 312013929070.dkr.ecr.ap-northeast-1.amazonaws.com/panda-cronjob:server-c601cee
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 3
  suspend: false