apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: xytest
  namespace: test
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: xytest
            # command: {cronjob_cmd}
            image: 312013929070.dkr.ecr.ap-northeast-1.amazonaws.com/panda-cronjob:xytest-c299cae
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 3
  suspend: false
