name: 'build and push docker image'

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest

    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v2
        with:
          registry: ghcr.io
          username: xuyang1996
          password: ${{ secrets.ACCESS_TOKEN }}
          repository: xuyang1996/server
          tags: ${{ github.sha }}