name: build-push-deploy-docker-image

on:
  push:
    branches:
    - main

jobs:
  build-push-deploy-docker-image:
    name: build-push-deploy-docker-image
    runs-on: ubuntu-latest

    steps:
      - name: check-out-code
        uses: actions/checkout@v2

      - name: build-push-docker-image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: server
          tags: ${{ github.sha }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACCESS_TOKEN }}
        # docker pull ghcr.io/xuyang1996/server:67028d43c1f7d83c4c0f8b9fee7a89bf9ac767e3

      - name: deploy-docker-image-to-aws-eks
        uses: cancue/eks-action@v0.0.2
        env:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ap-northeast-1
          cluster_name: panda-k8s
        with:
          args: |
            image=ghcr.io/${{ github.actor }}/server:${{ github.sha }}
            time=`date`
            echo "${time}, prepare to update image: ${image}"

            kubectl set image ds server server=${image}
            kubectl get pod

